repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff (local)
        entry: poetry run ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: ruff-format (local)
        entry: poetry run ruff format
        language: system
        types: [python]

#  - repo: local
#    hooks:
#      - id: mypy
#        name: mypy (local)
#        entry: poetry run mypy
#        language: system
#        types: [python]


  - repo: local
    hooks:
      - id: pytest
        name: pytest (local)
        entry: poetry run pytest
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        args: [ "--cov=src", "--cov-report=term" ]
        require_serial: true