repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi ]
        exclude: |
          (?x)^(
            .venv/|
            __pycache__/|
            .git/|
            (^|/)config\.py|
            .env|
            poetry\.lock
          )$

      - id: ruff-format
        types_or: [ python, pyi ]
        exclude: |
          (?x)^(
            .venv/|
            __pycache__/|
            .git/|
            (^|/)config\.py|
            .env|
            poetry\.lock
          )$


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        types_or: [ python, pyi ]
        exclude: |
          (?x)^(
            .venv/|
            __pycache__/|
            .git/|
            (^|/)config\.py|
            .env|
            poetry\.lock
          )$