services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: telegram-bot-container
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped

  tests:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: test-bot-container
    command: ["poetry", "run", "pytest"]
    volumes:
      - .:/app
    env_file:
      - .env
