services:
  bot:
    profiles:
      - dev
    build: .
    container_name: telegram-bot-container
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend
    restart: unless-stopped

  db:
    profiles:
      - dev
    image: postgres:17-alpine
    container_name: postgres-container
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - backend
    restart: unless-stopped


  tests:
    profiles:
      - test
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: test-bot-container
    command: [ "poetry", "run", "pytest" ]
    volumes:
      - .:/app
    depends_on:
      - db_test
    env_file:
      - .env
    environment:
      - POSTGRES_DB=db_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - DB_HOST=db_test
      - DB_PORT=5432
      - DB_NAME=db_test
      - DB_USER=user
      - DB_PASS=pass
    networks:
      - backend

  db_test:
    profiles:
      - test
    env_file:
      - .env
    environment:
      - POSTGRES_DB=db_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - DB_HOST=db_test
      - DB_PORT=5432
      - DB_NAME=db_test
      - DB_USER=user
      - DB_PASS=pass
    image: postgres:17-alpine
    container_name: postgres-container-test
    networks:
      - backend



volumes:
  db-data:

networks:
  backend:
    driver: bridge

