"""Добавлена таблица schedules

Revision ID: e620193cd1a9
Revises: ed35d43e9e61
Create Date: 2025-07-01 17:54:28.775775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e620193cd1a9'
down_revision: Union[str, None] = 'ed35d43e9e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('visit_datetime', sa.DateTime(), nullable=False),
    sa.Column('visit_duration', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('is_booked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_telegram_id'], ['users.telegram_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    # ### end Alembic commands ###
