"""change columns in table users

Revision ID: ed35d43e9e61
Revises: 04489ea7c838
Create Date: 2025-06-11 09:12:42.391211

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed35d43e9e61'
down_revision: str | None = '04489ea7c838'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12),
               existing_nullable=True)
    op.drop_index(op.f('ind_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ind_users_username'), table_name='users')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ind_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ind_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
