"""Add field is_approved in TABLE schedules

Revision ID: 23c133c5b8d9
Revises: 9370fa5a3d4c
Create Date: 2025-07-22 14:17:15.587442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c133c5b8d9'
down_revision: Union[str, None] = '9370fa5a3d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('is_approved', sa.Boolean(), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'is_approved')
    # ### end Alembic commands ###
