"""create TABLE days_off

Revision ID: aa836b83b09c
Revises: 9552f87ce588
Create Date: 2025-07-25 13:09:10.065938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa836b83b09c'
down_revision: Union[str, None] = '9552f87ce588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_off',
    sa.Column('day_off', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('id_sequence')"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_days_off_day_off'), 'days_off', ['day_off'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_days_off_day_off'), table_name='days_off')
    op.drop_table('days_off')
    # ### end Alembic commands ###
